from config import *

SECRET_KEY = APPCONFIG['SECRET_KEY']
MAX_CONTENT_LENGTH = 5 * 1024 * 1024 # 5MB

DROPBOX_KEY = APPCONFIG['DROPBOX_KEY']
DROPBOX_SECRET = APPCONFIG['DROPBOX_SECRET'] 
DROPBOX_ACCESS_TYPE = APPCONFIG['DROPBOX_ACCESS_TYPE']
DROPBOX_ACCESS_TOKEN = APPCONFIG['DROPBOX_ACCESS_TOKEN']

MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 465
MAIL_USERNAME = APPCONFIG['MAIL_USERNAME']
MAIL_PASSWORD = APPCONFIG['MAIL_PASSWORD']
MAIL_USE_TLS = False
MAIL_USE_SSL = True 
MAIL_ASCII_ATTACHMENTS = True
MAIL_DEFAULT_SENDER = APPCONFIG['MAIL_DEFAULT_SENDER']
MAIL_SENDER = APPCONFIG['MAIL_SENDER']

SERVER_BASE_ADDRESS = APPCONFIG['SERVER_BASE_ADDRESS']